acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('delete/', views.delete, name="delete"),
    path('signup/', views.signup, name="signup"),
    path('update/',views.update, name="update"),

]

config/urls.py

from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import settings
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('acc/',include('acc.urls')),
    path('product/', include("product.urls")),
    path('live/', include("live.urls")),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


product/urls.py
from django.urls import path
from . import views


app_name = "product"
urlpatterns =[
    path('index/', views.index, name="index"),
    path('detail/<bpk>', views.detail, name="detail"),
    path('delete/<bpk>', views.delete, name="delete"),
    path('create/', views.create, name="create"),
    path('update/<bpk>', views.update, name="update"),
    path('creview/<bpk>', views.creview, name="creview"),
    path('dreview/<bpk>/<rpk>', views.dreview, name="dreview"),
]

acc/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class User(AbstractUser): 
    pass

acc/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .models import User

def index(request):
    return render(request,'acc/index.html')
# Create your views here.

def login_user(request):
    if request.method == "POST" :
        un = request.POST.get("uname")
        up = request.POST.get("upass")
        u = authenticate(username=un, password=up)
        if u : 
            login(request,u) 
            return redirect("acc:index")

    return render(request,'acc/login.html')

def logout_user(request):
    logout(request)  
    return redirect("acc:index")

def profile(request):
    return render(request, "acc/profile.html")

def delete(request):
    request.user.delete()
    return redirect("acc:index") 

def signup(request):
    if request.method=="POST":
        un = request.POST.get("uname")
        up = request.POST.get("upass")
        ue = request.POST.get("umail")
        uf = request.POST.get("fname")
        ul = request.POST.get("lname")
        User.objects.create_user(username=un, password=up, email=ue,
        first_name=uf, last_name=ul)
        return redirect("acc:index")
    return render(request,"acc/signup.html")       

def update(request):
    if request.method=="POST":
        u = request.user
        un = request.POST.get("uname") 
        ue = request.POST.get("umail")
        uf = request.POST.get("fname")
        ul = request.POST.get("lname")    
        u.email = ue
        u.first_name = uf
        u.last_name = ul
        u.save()

    return render(request,"acc/update.html")

templates/acc/index.html
{% extends 'base.html' %}
{% block con %}
{% load static %}	

<!DOCTYPE html>
<html>	
  <head>	  
    <title>title</title>	 
    <!-- Bootstrap cdn 설정 -->      
    <!-- 이벤트 배너 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css">
<!-- 문제 발생 CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>	  
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
      .navbar-expand-sm .navbar-collapse {
          display: flex !important;
      }
      .navbar {
          border-radius: 0px;
      }

      div.loginbox {
        width: 0%;
        float: left;
        box-sizing: border-box;
        background: #adedc6;
      }
      div.bannerbox {
        width: 100%;
        float: right;
        box-sizing: border-box;
        background: #ecece9;
      }
    </style>
    

  </head>
    <form>
        <div class="container">
            <div class="row"> 
                <div class="col-lg-3"> <img src={% static "/logo/logo2.png" %} style= "width:150px; height: 150px;"/>
                </div>
                <div class="col-lg-7 mt-5">
                    <input type="text" name="kw" value="{{kw}}" class="form-control">
                </div>
                <div class="col-lg-2 mt-5 text-center ">
                    <a href="{% url 'product:index' %}" name="kw" value="{{ kw }}"><button class="btn btn-dark" type="button">검색</button></a>
                </div>
            </div>
        </div>    
    </form>

  <body>  
  <!-- carousel를 구성할 영역 설정 -->  
  <div style="background-color:rgb(208, 211, 211)">
    <div class="bannerbox">
      <div style="width: 750px; margin: auto; ">    
      <!-- carousel를 사용하기 위해서는 class에 carousel와 slide 설정한다. -->    
      <!-- carousel는 특이하게 id를 설정해야 한다.-->    
        <div id="carousel-example-generic" class="carousel slide"  >      
          <!-- carousel의 지시자 -->      <!-- 지시자라고는 하는데 ol태그의 class에 carousel-indicators를 넣는다. -->      
          <ol class="carousel-indicators">        
            <!-- li는 이미지 개수만큼 추가하고 data-target은 carousel id를 가르킨다. -->        
            <!-- data-slide-to는 순서대로 0부터 올라가고 0은 active를 설정한다. -->        
            <!-- 딱히 이 부분은 옵션별로 설정하게 없다. -->        
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>        
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>      
          </ol>      <!-- 실제 이미지 아이템 -->      <!-- class는 carousel-inner로 설정하고 role은 listbox에서 설정한다. -->      
          <div class="carousel-inner" role="listbox">        
            <!-- 이미지의 개수만큼 item을 만든다. 중요한 포인트는 carousel-indicators의 li 태그 개수와 item의 개수는 일치해야 한다. -->        
            <div class="item active">          <!-- 아미지 설정- -->          
            <img src={% static "event/블랙프라이데이.jpg" %} style="width: 900px; height: 500px;">         
            <!-- 캡션 설정 (생략 가능) -->          <!-- 글자 색은 검은색 -->          
              <div class="carousel-caption" style="color:black;">               
              </div>       
            </div>        
            <div class="item">          
              <img src={% static "event/타임세일.png" %} style="width: 900px; height: 500px;">          
              <div class="carousel-caption" style="color:black;">           
              </div>        
            </div>      
          </div>     
          <!-- 왼쪽 화살표 버튼 -->     
          <!-- href는 carousel의 id를 가르킨다. -->      
          <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">        
          <!-- 왼쪽 화살표 -->        
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>      
          </a>      <!-- 오른쪽 화살표 버튼 -->      <!-- href는 carousel의 id를 가르킨다. -->      
          <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">        <!-- 오른쪽 화살표 -->        
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>      
          </a>    
        </div>  
      </div>
    </div>
  </div>


  


    <script>    
    
      $(function(){
             // 이미지 슬라이드 컨트롤를 사용하기 위해서는 carousel를 실행해야한다.     
        $('#carousel-example-generic').carousel({
            // 슬리아딩 자동 순환 지연 시간        // false면 자동 순환하지 않는다.
            interval: 100,        
            // hover를 설정하면 마우스를 가져대면 자동 순환이 멈춘다.
            pause: "hover",        // 순환 설정, true면 1 -> 2가면 다시 1로 돌아가서 반복
            wrap: true,        // 키보드 이벤트 설정 여부(?)
            keyboard : true
              });
            });  
    </script>
</body>	
</html>



{% endblock %}
    

templates/acc/login.html

<!DOCTYPE html>
<html>	
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500&display=swap" rel="stylesheet"> 

  <head>
    <style>
body {
  align-items: center;
  background-color: rgb(200, 201, 181);
  display: flex;
  justify-content: center;
  height: 100vh;
}

.form {
  background-color: #165638;
  border-radius: 20px;
  box-sizing: border-box;
  height: 600px;
  padding: 20px;
  width: 320px;
}

.title {
  color: #eee;
  font-family: sans-serif;
  font-size: 36px;
  font-weight: 600;
  margin-top: 30px;
}

.subtitle {
  color: #eee;
  font-family: sans-serif;
  font-size: 16px;
  font-weight: 600;
  margin-top: 10px;
}

.input-container {
  height: 50px;
  position: relative;
  width: 100%;
}

.ic1 {
  margin-top: 40px;
}

.ic2 {
  margin-top: 30px;
}

.input {
  background-color: #303245;
  border-radius: 12px;
  border: 0;
  box-sizing: border-box;
  color: rgb(255, 255, 255);
  font-size: 18px;
  height: 100%;
  outline: 0;
  padding: 4px 20px 0;
  width: 100%;
}

.cut {
  background-color: #dee1df;
  border-radius: 10px;
  height: 20px;
  left: 20px;
  position: absolute;
  top: -20px;
  transform: translateY(0);
  transition: transform 200ms;
  width: 96px;
}

.cut-short {
  width: 50px;
}

.input:focus ~ .cut,
.input:not(:placeholder-shown) ~ .cut {
  transform: translateY(8px);
}

.placeholder {
  color: #65657b;
  font-family: sans-serif;
  left: 20px;
  line-height: 14px;
  pointer-events: none;
  position: absolute;
  transform-origin: 0 50%;
  transition: transform 200ms, color 200ms;
  top: 20px;
}

.input:focus ~ .placeholder,
.input:not(:placeholder-shown) ~ .placeholder {
  transform: translateY(-30px) translateX(10px) scale(0.75);
}

.input:not(:placeholder-shown) ~ .placeholder {
  color: #808097;
}

.input:focus ~ .placeholder {
  color: #0a3a12;
}

.submit {
  background-color: rgb(3, 40, 23);
  border-radius: 12px;
  border: 0;
  box-sizing: border-box;
  color: #eee;
  cursor: pointer;
  font-size: 18px;
  height: 50px;
  margin-top: 38px;
    outline: 0;
  text-align: center;
  width: 100%;
}

.submit:active {
  background-color: rgb(5, 27, 16);
}

        </style>
    </head>
</html>	  


<!-- 
<div class="text-center">
    <br><br>
    <h1 class="display-10 fw-bold">KG Commerce에 오신 것을 환영합니다!</h1>
    <br> -->

    
<!-- 
    <form method="post">
        {% csrf_token %}
        <input type="text" name="uname" placeholder="Input your ID"><br><br>
        <input type="password" name="upass" placeholder="Input yout Password"><br><br>
        <button class="btn btn-dark btn-secondary" style="font-weight: bold;">LOGIN</button>


        <a href="{% url 'acc:index' %}"><button class="btn btn-dark btn-secondary" type="button" style="font-weight: bold;">HOME</button></a>

    </form> -->

</div>

<div class="form">
    <form method="post">
        {% csrf_token %}
    <div class="title">Welcome</div>
    <div class="input-container ic1">
      <input id="firstname" class="input" type="text" placeholder=" " name="uname" />
      <div class="cut"></div>
      <label for="firstname" class="placeholder">Your ID</label>
    </div>
    <div class="input-container ic2">
      <input id="lastname" class="input" type="text" placeholder=" " name="upass" />
      <div class="cut"></div>
      <label for="lastname" class="placeholder">Your Password</label>
    </div>

    <button type="text" class="submit">Login</button>
    </form>
    <a href="{% url 'acc:index' %}"><button type="button" class="submit">HOME</button></a>
    <a href="{% url 'acc:signup' %}"><button type="button" class="submit">Sign up</button></a>
  </div>

templates/acc/profile.html
{% extends 'base.html' %}
{% block con %}


<h1>{{ user }}'s profile</h1>

USERNAME <input type="text" value = "{{user.username}}" disabled><br><br>
EMAIL <input type="text" value = "{{user.email}}" disabled><br><br>
FIRST NAME <input type="text" value = "{{user.first_name}}"disabled><br><br>
LAST NAME <input type="text" value = "{{user.last_name}}" disabled><br><br>
<a href="{% url 'acc:index' %}"><button>HOME</button></a>
<a href="{% url 'acc:update' %}"><button>MOD</button></a>
<a href="{% url 'acc:delete' %}"><button>DEL</button></a>

{% endblock %}

templates/acc/signup.html
{% extends 'base.html' %}
{% block con %}
<br><br>

<div class="text-center">
    <h1 class="display-10 fw-bold">회원 가입</h1><br>

    <form method="post">
        {% csrf_token %}
        ID : <input type="text" name="uname" placeholder="input your ID"><br><br>
        PW : <input type="password" name="upass" placeholder="input your P/W"><br><br>
        Email : <input type="text" name="umail" placeholder="example@example.com"><br><br>
        이름 : <input type="text" name="fname" placeholder="길동"><br><br>
        성 : <input type="text" name="lname" placeholder="홍"><br><br>
        <button class="btn btn-dark btn-secondary" style="font-weight: bold;">가입</button>
    </form>
</div>
{% endblock %}

templates/acc/update.html
{% extends 'base.html' %}
{% block con %}

<h1>{{ user }}'s UPDATE PAGE</h1>

<form method="post">
    {% csrf_token %}
USERNAME <input type="text" name="uname" value="{{ user }}" disabled><br><br>
PASSWORD <input type="password" name="upass"><br><br>
EMAIL <input type="text" name="umail" value="{{ user.email }}"><br><br>
FIRST_NAME<input type="text" name="fname" value="{{ user.first_name }}"><br><br>
LAST_NAME<input type="text" name="lname" value="{{ user.last_name }}"><br><br>

<button class="btn btn-dark btn-secondary" style="font-weight: bold;">등록</button>
</form>

{% endblock %}