acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('delete/', views.delete, name="delete"),
    path('signup/', views.signup, name="signup"),
    path('update/',views.update, name="update"),

]

config/urls.py

from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import settings
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('acc/',include('acc.urls')),
    path('product/', include("product.urls")),
    path('live/', include("live.urls")),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


product/urls.py
from django.urls import path
from . import views


app_name = "product"
urlpatterns =[
    path('index/', views.index, name="index"),
    path('detail/<bpk>', views.detail, name="detail"),
    path('delete/<bpk>', views.delete, name="delete"),
    path('create/', views.create, name="create"),
    path('update/<bpk>', views.update, name="update"),
    path('creview/<bpk>', views.creview, name="creview"),
    path('dreview/<bpk>/<rpk>', views.dreview, name="dreview"),
]

product/models.py
from django.db import models
from acc.models import User


# Create your models here.

class Product(models.Model):
    product = models.CharField(max_length=200)
    seller = models.ForeignKey(User, on_delete=models.CASCADE, related_name="seller")
    shortcon = models.TextField(max_length=30)
    content = models.TextField()
    pubdate = models.DateTimeField()
    picture = models.ImageField(upload_to= "product/", blank=True, null=True)
    viewcount = models.IntegerField(default=0)
    sellcount = models.IntegerField(default=0)
    price = models.IntegerField()
    category_choice = (
        ('ELC', '가전'),
        ('FOD', '음식'),
        ('CLO', '의류'),
        ('LIV', '생필품')
    )
    cate = models.CharField(max_length=3, choices=category_choice)

    def summary(self):
        if len(self.content) > 20:
            return f"{self.content[:20]} ...자세히 보기"
        return self.content

    def __str__(self):
        return f"{self.product}_{self.seller}"

    def getpic(self):
        if self.picture:
            return self.picture.url
        return "/media/noimage.jpg"

    def cate_choice(self) :
        
        return f"{self.category_choice[1]}"

    def cate_name(self) : 
        cho = self.cate

        return f"{self.cate}"

# class Reply(models.Model):
#     board = models.ForeignKey(Product, on_delete=models.CASCADE)
#     replyer = models.ForeignKey(User, on_delete=models.CASCADE)
#     comment = models.TextField()

#     def __str__(self):
#       return f"{self.product}_{self.replyer}"

class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    replyer = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()

    def __str__(self):
        return f"{self.product}_{self.replyer}"

product/views.py

from django.shortcuts import render, redirect
from .models import Product, Review
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib import messages
# Create your views here.


def index(request):
    pg = request.GET.get("page", 1)
    cate = request.GET.get("cate", "")
    kw = request.GET.get("kw", "")

    if kw:
        if cate == "prod":
            b = Product.objects.filter(product__startswith=kw)
        elif cate == "sel":
            from acc.models import User
            try:
                u = User.objects.get(username=kw)
                b = Product.objects.filter(seller=u)
            except:
                b = Product.objects.none()
        elif cate == "con":
            b = Product.objects.filter(content__contains=kw)
        else:
            b = Product.objects.none()
    else:
        b = Product.objects.all()

    pag = Paginator(b, 5)
    obj = pag.get_page(pg)
    context = {
        "bset": obj,
        "cate": cate,
        "kw": kw,
        "b": b
    }
    return render(request, "product/index.html", context)




def update(request, bpk):
    b = Product.objects.get(id=bpk)

    if b.seller != request.user:
        return redirect("product:index")

    if request.method == "POST":
        s = request.POST.get("prod")
        sc = request.POST.get("scon")
        c = request.POST.get("con")
        b.product = s
        b.content = c
        b.shortcon = sc
        b.save()
        return redirect("product:detail", bpk)
    context = {
        "b":b
    }
    return render(request, "product/update.html", context)

def create(request):
    if request.method == "POST":
        p = request.POST.get("prod")
        ct = request.POST.get("cate")
        sc = request.POST.get("scon")
        c = request.POST.get("con")
        pi = request.FILES.get("pic")
        pr = request.POST.get("price")
        # cate = Product.objects.get(name=cate)
        # print(Product.cate_choice)
        Product(product=p, price=pr, cate = ct,  content=c, picture=pi, shortcon= sc,
        seller=request.user, pubdate=timezone.now()).save()
        # print(Product.objects.all())
        return redirect("product:index")
    cate = Product.category_choice
    context = { 
        "cate" : cate
    }
    print(context)
    return render(request, "product/create.html", context)

def delete(request, bpk):
    b = Product.objects.get(id=bpk)
    if request.user == b.seller:        
        b.picture.delete()
        b.delete()
    else:
        pass 
    return redirect("product:index")



def dreview(request, bpk, rpk):
    c = Review.objects.get(id=rpk)
    if c.replyer == request.user:
        c.delete()
    else:
        pass 
    return redirect("product:detail", bpk)


def creview(request, bpk):
    p = Product.objects.get(id=bpk)
    c = request.POST.get("com")
    Review(product=p, replyer=request.user, comment=c).save()
    return redirect("product:detail", bpk)


def detail(request, bpk):
    b = Product.objects.get(id=bpk)
    c = b.review_set.all()
    context = {
        "b": b,
        "cset" : c
    }
    b.viewcount += 1
    b.save()
    return render(request, "product/detail.html", context )

templates/product/create.html
{% extends 'base.html' %}
{% block con %}
    <div class="container mt-5 mb-5" style="font-size: 20px; font-weight: bold;">
        <h1><b>게시물 작성</b></h1>
        <form method="post" action = "{% url 'product:create' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3 mt-5">
                <label class="form-label">제품명</label>
                <input type="text" name="prod" class="form-control">
            </div>
            <div id = "container" class="mb-3 mt-5">
                <label class="form-label">카테고리</label>                
                <div class="col-lg-2">
                    <select class="form-select mb-3" name="cate" aria-label=".form-select-lg example">
                        {% for i in cate %} 
                        <option name="cate" > {{ i }}</option>
                        {% endfor %}
                        <!-- <option value=f"sel" {% if cate == "wri" %} selected {% endif %}>작성자</option>
                        <option value="con" {% if cate == "con" %} selected {% endif %}>내용</option> -->
                    </select>
                </div>
            </div>
            <div class="mb-3">
                <label class="form-label">제품 이미지</label>
                <input type="file" name="pic" class="form-control" >
            <div class="mb-3">
                <label class="form-label">SELLER</label>
                <input type="text" class="form-control" value="{{ user }}" disabled>
            </div>
            <div class="mb-3">
                <label class="form-label">가격</label>
                <textarea class="form-control" name="price" style="height: 10px;"></textarea>
            </div>
            <div class="mb-3">
                <label class="form-label">간략한 소개(20자 이내)</label>
                <textarea class="form-control" name="scon" style="height: 150px;"></textarea>
            </div>
            <div class="mb-3">
                <label class="form-label">제품 소개</label>
                <textarea class="form-control" name="con" style="height: 150px;"></textarea>
            </div>
            <div class="text-end mt-3">
                <button class="btn btn-dark">생성</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/product/detail.html
{% extends 'base.html' %}
{% block con %}
<!-- Product section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{ b.getpic }}" style = "width:500px; height:500px;" /></div>
            <div class="col-md-6">
                <div class="small mb-1">{{ b.cate }}</div>
                <h1 class="display-5 fw-bolder">{{ b.product }}</h1>
                <div class="fs-5 mb-5">
                    <span class="text-decoration-line-through">{{ b.price }}\</span>
                    <span>{{ b.price }}\</span>
                </div>
                <p class="lead">{{ b.content }}</p>
                <div class="d-flex">
                    <input class="form-control text-center me-3" id="inputQuantity" type="num" value="1" style="max-width: 3rem" />
                    <button class="btn btn-outline-dark flex-shrink-0" type="button">
                        <i class="bi-cart-fill me-1"></i>
                        Buy now
                    </button>
                    {% if user == b.seller %}
                    <a href="{% url 'product:update' b.id %}"><button class="btn btn-dark">수정</button></a>
                    <a href="{% url 'product:delete' b.id %}"><button class="btn btn-danger">삭제</button></a>
                    {% endif %}
                </div>
            </div>
        </div>
 
        <hr>

        <form method="post" action="{% url 'product:creview' b.id %}">
            {% csrf_token %}
            <div class="row mt-5 mb-5">
                <div class="col-lg-10">
                    <input type="text" name="com" class="form-control">
                </div>
                <div class="col-lg-2">
                    <button class="btn btn-dark" style="width: 100%;">댓글작성</button>
                </div>
            </div>
        </form>
       
        {% if cset %}
        <div class="row text-center">
            
            {% for i in cset %}
                <div class="col-lg-4 mt-5">
                    
                        <b>{{ i.replyer }}</b>
                
                </div>
                <div class="col-lg-8 mt-5">
                    <textarea class="form-control" style="height: 100px;" disabled>{{ i.comment }}</textarea>
                    <div class="text-end mt-3">
                        {% if i.replyer == user %}
                            <a href="{% url 'product:dreview' b.id i.id %}" class="btn btn-danger">삭제</a>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <h4>첫번째 리뷰를 달아주세요 </h4>
    {% endif %}

    </div>
</section>
<!-- Related items section-->
<section class="py-5 bg-light">
    <div class="container px-4 px-lg-5 mt-5">
        <h2 class="fw-bolder mb-4">Related products</h2>
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            <div class="col mb-5">
                <div class="card h-100">
                    <!-- Product image-->
                    <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">Fancy Product</h5>
                            <!-- Product price-->
                            $40.00 - $80.00
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">View options</a></div>
                    </div>
                </div>
            </div>
            <div class="col mb-5">
                <div class="card h-100">
                    <!-- Sale badge-->
                    <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                    <!-- Product image-->
                    <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">Special Item</h5>
                            <!-- Product reviews-->
                            <div class="d-flex justify-content-center small text-warning mb-2">
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                            </div>
                            <!-- Product price-->
                            <span class="text-muted text-decoration-line-through">$20.00</span>
                            $18.00
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
                    </div>
                </div>
            </div>
            <div class="col mb-5">
                <div class="card h-100">
                    <!-- Sale badge-->
                    <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                    <!-- Product image-->
                    <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">Sale Item</h5>
                            <!-- Product price-->
                            <span class="text-muted text-decoration-line-through">$50.00</span>
                            $25.00
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
                    </div>
                </div>
            </div>
            <div class="col mb-5">
                <div class="card h-100">
                    <!-- Product image-->
                    <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">Popular Item</h5>
                            <!-- Product reviews-->
                            <div class="d-flex justify-content-center small text-warning mb-2">
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                            </div>
                            <!-- Product price-->
                            $40.00
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
</footer>
<!-- Bootstrap core JS-->
<!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script> -->
<!-- Core theme JS-->
<!-- <script src="js/scripts.js"></script> -->
</body>
</html>

{% endblock %}

templates/product/detail2.html
{% extends 'base.html' %}
{% block con %}
    <div class="container mt-5 mb-5">
        <h1><b>{{b.product}}</b></h1>

        <div class="row mt-5">
            
            <div class="col-lg-1">
            </div>

            <div class="col-lg-4">
                <img src= "{{ b.getpic }}" style = "width: 350px; height: 350px;" >
            </div>
            <div class="col-lg-4">
                <textarea class="form-control" style="height: 350px;" disabled>{{ b.content }}</textarea>
            </div>
            
            <div class="col-lg-2" style="margin: auto;">
                <div class="text-center mt-1">
                    <h4>판매자 : <b>{{ b.seller }}</b></h4>
                </div>
                <div class="text-center mt-1">
                    <h4>조회수 : <b>{{ b.viewcount }}</b></h4>
                </div>
                
                <div class="text-end mt-2" style="font-size:small">
                    등록일 : {{ b.pubdate | date:'Y년 n월 j일 H:i' }} 
                </div>
            </div>
        </div>


        <div class="mt-3 text-end">
            <a href="{% url 'product:index' %}" class="btn btn-dark">메인</a>
            {% if user == b.seller %}
                <a href="{% url 'product:update' b.id %}"><button class="btn btn-secondary">수정</button></a>
                <a href="{% url 'product:delete' b.id %}"><button class="btn btn-danger">삭제</button></a>
            {% endif %}
        </div>


        <hr>

        
    </div>

{% endblock %}

templates/product/index.html
{% extends 'base.html' %}
{% block con %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>KG Commerce</title>
    <!-- Favicon-->
    <!-- <link rel="icon" type="image/x-icon" href="/assets/favicon.ico" /> -->
    <link rel="icon" type="image/x-icon" href='{% static "/assets/favicon.ico" %}' />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <!-- <link href="css/styles.css" rel="stylesheet" /> -->
    <link href='{% static "css/styles.css" %}' rel="stylesheet" />
</head>

  <!-- Header-->
  <header class="bg-dark py-5">
      <div class="container px-4 px-lg-5 my-5">
          <div class="text-center text-white">
              <h1 class="display-4 fw-bolder">KG Commerce</h1>
              <p class="lead fw-normal text-white-50 mb-0">With our awesome Price</p>
          </div>
      </div>
  </header>
  <!-- Section-->
  
    
  <section class="py-5">
      <div class="container px-4 px-lg-5 mt-5">
          <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% if b %}
            {% for i in b %} 
            <div class="col mb-5">
                  <div class="card h-100 jus">
                      <!-- Sale badge-->
                      <div class="badge btn-danger text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                      <!-- Product image-->
                      <img class="card-img-top" src="{{ i.getpic }}" style = "width: 206px; height: 250px;" />
                      <!-- Product details-->
                      <div class="card-body p-4">
                          <div class="text-center">
                              <!-- Product name-->
                              <h5 class="fw-bolder"><a href="{% url 'product:detail' i.id %}">{{ i.product }}</a></h5>
                              <!-- Product price-->
                              {{ i.price }} \
                          </div>
                      </div>
                      <!-- Product actions-->
                      <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
			      <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">조회수 {{ i.viewcount }}</a></div>
                      </div>
                  </div>
              </div>
              {% endfor %}
              {% else %}
              <h5> 표시할 제품이 없습니다. </h5>
              {% endif %}
          </div>
      </div>
  </section>
  <!-- Footer-->
  <footer class="py-5 bg-dark">
      <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
  </footer>
  <!-- Bootstrap core JS-->
  <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script> -->
  <!-- Core theme JS-->
  <!-- <script src="js/scripts.js"></script> -->
</body>
</html>

{% endblock %}

templates/product/index2.html
{% extends 'base.html' %}
{% block con %}
{% load mathfilters %}
    <div class="container mt-5 mb-5">
        <h1><b>KG Commerce Product</b></h1>

        <div class="text-end">
            <a href="{% url 'product:create' %}" class="btn btn-dark">CREATE</a>
        </div>


        <!-- 테이블 -->
        <table class="table mt-3 table-hover">
            <thead style="background-color: black; color:white; font-size: 20px;">
                <tr>
                    <th scope="col">NO</th>
                    <th scope="col">Image</th>
                    <th scope="col">제품명</th>
                    <th scope="col">제품 정보</th>
                    <th scope="col">판매자</th>
                    <th scope="col">조회수</th>
                    <th scope="col">판매수</th>
                </tr>
            </thead>
            <tbody>
                {% if b %}
                    {% for i in b %}
                        <tr>
                            <th scope="row">{{ bset.start_index|add:forloop.counter0 }}</th>
                            <td><img src= "{{ i.getpic }}" style = "width: 10px; height: 10px;" ></td>
                            <td><a class="sub" href="{% url 'product:detail' i.id %}">{{ i.product }}</a></td>
                            <td>{{ i.shortcon }}</td>
                            <td>{{ i.seller }}</td>
                            <td>{{ i.viewcount }}</td>
                            <td>{{ i.sellcount }}</td>
                            
                        </tr>
                    {% endfor %}
                {% else %}
                    {% if kw %}
                        <tr class="text-center">
                            <th colspan="5"><h3><b>검색결과가 없습니다.</b></h3></th>
                        </tr>
                    {% else %}
                        <tr class="text-center">
                            <th colspan="5">등록된 제품이 존재하지 않습니다.</th>
                        </tr>
                    {% endif %}
                {% endif %}
            </tbody>
        </table>

        <nav id="pag" class="mt-5" aria-label="Page navigation example">
            <ul class="pagination justify-content-center">

                {% if bset.has_previous %}
                    <li class="page-item">
                        <a href="?page=1&cate={{cate}}&kw={{kw}}" class="page-link">처음</a>
                    </li>
                    <li class="page-item">
                        <a href="?page={{bset.previous_page_number}}&cate={{cate}}&kw={{kw}}" class="page-link">이전</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">처음</a>
                    </li>
                    <li class="page-item disabled">
                        <a class="page-link">이전</a>
                    </li>
                {% endif %}
                

                {% for i in bset.paginator.page_range %}
                    {% if i >= bset.number|sub:5 and bset.number|add:4 >= i %}
                        <li class="page-item {% if bset.number == i %} active {% endif %}">
                            <a class="page-link" href="?page={{i}}&cate={{cate}}&kw={{kw}}">{{i}}</a>
                        </li>
                    {% endif %}
                {% endfor %}

                {% if bset.has_next %}
                    <li class="page-item">
                        <a href="?page={{bset.next_page_number}}&cate={{cate}}&kw={{kw}}" class="page-link">다음</a>
                    </li>
                    <li class="page-item">
                        <a href="?page={{bset.paginator.num_pages}}&cate={{cate}}&kw={{kw}}" class="page-link">마지막</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">다음</a>
                    </li>
                    <li class="page-item disabled">
                        <a class="page-link">마지막</a>
                    </li>
                {% endif %}

            </ul>
        </nav>

        <form>
            <div class="row mt-4"> 
                <div class="col-lg-2">
                    <select class="form-select mb-3" name="cate" aria-label=".form-select-lg example">
                        <option value="prod" {% if cate == "prod" %} selected {% endif %}>제품명</option>
                        <option value="sel" {% if cate == "wri" %} selected {% endif %}>작성자</option>
                        <option value="con" {% if cate == "con" %} selected {% endif %}>내용</option>
                    </select>
                </div>
                <div class="col-lg-8">
                    <input type="text" name="kw" value="{{kw}}" class="form-control">
                </div>
                <div class="col-lg-2 text-center">
                    <button class="btn btn-dark">검색</button>
                    <a href="{% url 'product:index' %}" class="btn btn-dark">리셋</a>
                </div>
            </div>
        </form>









    </div>
    <style>
        .sub {
            color:black;
            text-decoration: none;
            font-size: 20px;
            font-weight: bold;
        }
        .sub:hover{
            color:red;
        }
    </style>



{% endblock %}

templates/product/update.html
{% extends 'base.html' %}
{% block con %}
    <div class="container mt-5 mb-5" style="font-size: 20px; font-weight: bold;">
        <h1><b>게시글수정</b></h1>
        <form method="post">
            {% csrf_token %}
            <div class="mb-3 mt-5">
                <label class="form-label">제품명</label>
                <input type="text" name="prod" value="{{ b.product }}" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">판매자</label>
                <input type="text" class="form-control" disabled value="{{ b.seller }}">
            </div>
            <div class="mb-3">
                <label class="form-label">짧은 소개</label>
                <textarea class="form-control" name="scon" style="height: 150px;">{{ b.content }}</textarea>
            </div>
            <div class="mb-3">
                <label class="form-label">CONTENT</label>
                <textarea class="form-control" name="con" style="height: 150px;">{{ b.content }}</textarea>
            </div>
            <div class="text-end mt-3">
                <button class="btn btn-dark">수정</button>
            </div> 
        </form>
    </div>
{% endblock %}