acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('delete/', views.delete, name="delete"),
    path('signup/', views.signup, name="signup"),
    path('update/',views.update, name="update"),

]

config/urls.py

from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import settings
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('acc/',include('acc.urls')),
    path('product/', include("product.urls")),
    path('live/', include("live.urls")),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


live/urls.py
from django.urls import path
from . import views


app_name = "live"
urlpatterns =[
    path('index/', views.index, name="index"),
    path('detail/<bpk>', views.detail, name="detail"),
    path('delete/<bpk>', views.delete, name="delete"),
    path('create/', views.create, name="create"),
    path('update/<bpk>', views.update, name="update"),
    path('creview/<bpk>', views.creview, name="creview"),
    path('dreview/<bpk>/<rpk>', views.dreview, name="dreview"),
    path('detail/<bpk>', views.detail, name="detail"),
    path('detail2', views.detail2, name="detail2"),
]

live/models.py
from django.db import models
from acc.models import User


# Create your models here.

class Live(models.Model):
    title = models.CharField(max_length=100)
    seller = models.ForeignKey(User, on_delete=models.CASCADE, related_name="liseller")
    shortcon = models.TextField(max_length=20)
    content = models.TextField()
    pubdate = models.DateTimeField()
    video = models.FileField(upload_to= "live/", blank=False, null=False)
    viewcount = models.IntegerField(default=0)
    sellcount = models.IntegerField(default=0)
    price = models.IntegerField()
    category_choice = (
        ('ELC', '가전'),
        ('FOD', '음식'),
        ('CLO', '의류'),
        ('LIV', '생필품')
    )
    cate = models.CharField(max_length=3, choices=category_choice)

    def getvideo(self):
        return self.video.url




class Reply(models.Model):
    title = models.ForeignKey(Live, on_delete=models.CASCADE )
    viewer = models.ForeignKey(User, on_delete=models.CASCADE)
    livecomment = models.TextField()

    def __str__(self):
        return f"{self.title}_{self.viewer}"

live/views.py

from django.shortcuts import render, redirect
from .models import Live, Reply
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib import messages
# Create your views here.


def index(request):
    pg = request.GET.get("page", 1)
    cate = request.GET.get("cate", "")
    kw = request.GET.get("kw", "")

    if kw:
        if cate == "prod":
            b = Live.objects.filter(product__startswith=kw)
        elif cate == "sel":
            from acc.models import User
            try:
                u = User.objects.get(username=kw)
                b = Live.objects.filter(liseller=u)
            except:
                b = Live.objects.none()
        elif cate == "con":
            b = Live.objects.filter(content__contains=kw)
        else:
            b = Live.objects.none()
    else:
        b = Live.objects.all()

    pag = Paginator(b, 5)
    obj = pag.get_page(pg)
    context = {
        "bset": obj,
        "cate": cate,
        "kw": kw,
        "b": b
    }
    return render(request, "live/index.html", context)




def update(request, bpk):
    b = Live.objects.get(id=bpk)

    if b.seller != request.user:
        return redirect("live:index")

    if request.method == "POST":
        s = request.POST.get("prod")
        sc = request.POST.get("scon")
        c = request.POST.get("con")
        b.title = s
        b.content = c
        b.shortcon = sc
        b.save()
        return redirect("live:detail", bpk)
    context = {
        "b":b
    }
    return render(request, "live/update.html", context)

def create(request):
    if request.method == "POST":
        t = request.POST.get("prod")
        ct = request.POST.get("cate")
        sc = request.POST.get("scon")
        c = request.POST.get("con")
        pi = request.FILES.get("pic")
        pr = request.POST.get("price")
        # cate = Product.objects.get(name=cate)
        # print(Product.cate_choice)
        Live(title=t, price=pr, cate = ct,  content=c, video=pi, shortcon= sc,
        seller=request.user, pubdate=timezone.now()).save()
        # print(Product.objects.all())
        return redirect("live:index")
    cate = Live.category_choice
    context = { 
        "cate" : cate
    }
    return render(request, "live/create.html", context)

def delete(request, bpk):
    b = Live.objects.get(id=bpk)
    if request.user == b.seller:        
        b.video.delete()
        b.delete()
    else:
        pass 
    return redirect("live:index")



def dreview(request, bpk, rpk):
    c = Reply.objects.get(id=rpk)
    if c.viewer == request.user:
        c.delete()
    else:
        pass 
    return redirect("live:detail", bpk)


def creview(request, bpk):
    p = Live.objects.get(id=bpk)
    c = request.POST.get("com")
    Reply(title=p, viewer=request.user, livecomment=c).save()
    return redirect("live:detail", bpk)


def detail(request, bpk):
    b = Live.objects.get(id=bpk)
    c = b.reply_set.all()
    context = {
        "b": b,
        "cset" : c
    }
    b.viewcount += 1
    b.save()
    
    return render(request, "live/detail.html", context )


def detail2(request):
    return render(request,"live/detail2.html")

templates/live/create.html
{% extends 'base.html' %}
{% block con %}
    <div class="container mt-5 mb-5" style="font-size: 20px; font-weight: bold;">
        <h1><b>게시물 작성</b></h1>
        <form method="post" action = "{% url 'live:create' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3 mt-5">
                <label class="form-label">제품명</label>
                <input type="text" name="prod" class="form-control">
            </div>
            <div id = "container" class="mb-3 mt-5">
                <label class="form-label">카테고리</label>                
                <div class="col-lg-2">
                    <select class="form-select mb-3" name="cate" aria-label=".form-select-lg example">
                        {% for i in cate %} 
                        <option name="cate" > {{ i }}</option>
                        {% endfor %}
                        <!-- <option value=f"sel" {% if cate == "wri" %} selected {% endif %}>작성자</option>
                        <option value="con" {% if cate == "con" %} selected {% endif %}>내용</option> -->
                    </select>
                </div>
            </div>
            <div class="mb-3">
                <label class="form-label">제품 이미지</label>
                <input type="file" name="pic" class="form-control" >
            <div class="mb-3">
                <label class="form-label">SELLER</label>
                <input type="text" class="form-control" value="{{ user }}" disabled>
            </div>
            <div class="mb-3">
                <label class="form-label">가격</label>
                <textarea class="form-control" name="price" style="height: 10px;"></textarea>
            </div>
            <div class="mb-3">
                <label class="form-label">간략한 소개(20자 이내)</label>
                <textarea class="form-control" name="scon" style="height: 150px;"></textarea>
            </div>
            <div class="mb-3">
                <label class="form-label">제품 소개</label>
                <textarea class="form-control" name="con" style="height: 150px;"></textarea>
            </div>
            <div class="text-end mt-3">
                <button class="btn btn-dark">생성</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/live/detail.html
{% extends 'base.html' %}
{% block con %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Insert title here</title>
        <style type="text/css">
            #fullscreen{
            	width: 100%;
            	height: 1500px;
            	
            }
            #screen1{
            	width: 50%;
            	height: 600px;
                box-sizing: border-box;
            	
            	float: left;
            }
            #screen1-1{
            	width: 200px;
            	height: 500px;
            	background-color: rgb(255, 0, 0);
            }
            #screen1-2{
            	width: 200px;
            	height: 100px;
            	background-color: yellow;
            }
            #screen2{
                margin-top: 100px;
            	width: 50%;
            	height: auto;
            	background-color: rgb(179, 187, 181);
            	float: right;
                box-sizing: border-box;
                border: 3px solid rgb(0,0,0) ;
            }
            #screen2-1{
            	width: 200px;
            	height: 200px;
            	background: #0ff;
            }
            #screen2-2{
            	width: 200px;
            	height: 400px;
            	background-color: green;
            }
            .balloon-left {
              position: relative;
              display: inline-block;
              margin: 1.5em 0 1.5em 15px;
              padding: 7px 10px;
              min-width: 120px;
              max-width: 40%;
              color: #555;
              font-size: 16px;
              background: #FFF;
              border: solid 3px #555;
              box-sizing: border-box;
            }
            .balloon-right {
              position: relative;
              display: inline-block;
              margin: 1.5em 0 1.5em 15px;
              padding: 7px 10px;
              min-width: 120px;
              max-width: 40%;
              color: #555;
              font-size: 16px;
              background: #FFF;
              border: solid 3px #555;
              box-sizing: border-box;
              float: right;
            }
            .balloon-left:before {
              content: "";
              position: absolute;
              top: 50%;
              left: -24px;
              margin-top: -12px;
              border: 12px solid transparent;
              border-right: 12px solid #FFF;
              z-index: 2;
            }

            .balloon-left:after {
              content: "";
              position: absolute;
              top: 50%;
              left: -30px;
              margin-top: -14px;
              border: 14px solid transparent;
              border-right: 14px solid #555;
              z-index: 1;
            }

            .balloon-left p {
              margin: 0;
              padding: 0;
            }
            </style>
    </head>


    <body>
        <div id="fullscreen">
        	<div id="screen1">


            <section class="py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="row gx-4 gx-lg-5 align-items-center">
                    <div class="content container">
                        <video autoplay controls loop muted width="auto" height="600px" preload="bbb" src = "{{ b.getvideo }}"  type="video/mp4"></video>
                    </div>
                <div class="col-md-6">
                    <div class="small mb-1">{{ b.cate }}</div>
                        <h1 class="display-6 fw-bolder">{{ b.title }}</h1>
                        <div class="fs-5 mb-5">
                            <span class="text-decoration-line-through">{{ b.price }}\</span>
                            <span>{{ b.price }}\</span>
                        </div>
                    <p class="lead">{{ b.content }}</p>
                    <div class="d-flex">
                        <input class="form-control text-center me-3" id="inputQuantity" type="num" value="1" style="max-width: 3rem" />
                        <button class="btn btn-outline-dark flex-shrink-0" type="button">
                            <i class="bi-cart-fill me-1"></i>
                            Buy now
                        </button>
                        {% if user == b.seller %}
                        <a href="{% url 'live:update' b.id %}"><button class="btn btn-dark">수정</button></a>
                        <a href="{% url 'live:delete' b.id %}"><button class="btn btn-danger">삭제</button></a>
                        {% endif %}
                    </div>
                </div>
            </div>

    	</div>

    	</div>
    	<div id="screen2">
            <div>
                <div>
            {% if cset %}
                

                {% for i in cset %}
                    
                        {% if i.viewer == b.seller %}
                        <div class="row">
                        <div class="balloon-left">
                            <b style="color: rgb(35, 48, 240); "> 🐱판매자-{{ i.viewer }} </b>
                            <div class="col-lg-8 mt-5">
                                {{ i.livecomment }}
                                <div class="text-end mt-3">
                                    {% if i.viewer == user %}
                                        <a href="{% url 'live:dreview' b.id i.id %}" class="btn btn-danger">삭제</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        </div>
                        {% else %}
                        <div class="row">
                        <div class="balloon-right">
                            <b> {{ i.viewer }} </b>
                            <div class="col-lg-8 mt-5">
                                {{ i.livecomment }}
                                <div class="text-end mt-3">
                                {% if i.viewer == user %}
                                <a href="{% url 'live:dreview' b.id i.id %}" class="btn btn-danger">삭제</a>
                                {% endif %}
                                </div>
                            </div>
                        </div>
                        </div>
                        {% endif %}
                
                {% endfor %}
                
            {% else %}
            </div>
            <h4> 채팅을 시작하세요 </h4>
            {% endif %}
    		</div>
    	

            <form method="post" action="{% url 'live:creview' b.id %}">
                {% csrf_token %}
                <div class="row mt-5 mb-5">
                    <div class="col-lg-10">
                        <input type="text" name="com" class="form-control">
                    </div>
                    <div class="col-lg-2">
                        <button class="btn btn-dark" style="width: 100%;">전송</button>
                    </div>
                </div>
            </form>
        </div>
        </div>
    </div>
    </body>
</html>


</div>
<hr>



<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
</footer>
<!-- Bootstrap core JS-->
<!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script> -->
<!-- Core theme JS-->
<!-- <script src="js/scripts.js"></script> -->
</body>
</html>

{% endblock %}

templates/live/index.html
{% extends 'base.html' %}
{% block con %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>KG Commerce</title>
    <!-- Favicon-->
    <!-- <link rel="icon" type="image/x-icon" href="/assets/favicon.ico" /> -->
   
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <!-- <link href="css/styles.css" rel="stylesheet" /> -->
    
</head>

  <!-- Header-->
  <header class="bg-dark py-5">
      <div class="container px-4 px-lg-5 my-5">
          <div class="text-center text-white">
              <h1 class="display-4 fw-bolder">KG Commerce</h1>
              <p class="lead fw-normal text-white-50 mb-0">With our awesome Price</p>
          </div>
      </div>
  </header>
  <!-- Section-->
  
    
  <section class="py-5">
      <div class="container px-4 px-lg-5 mt-5">
          <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% if b %}
            {% for i in b %} 
            <div class="col mb-5">
                  <div class="card h-100 jus">
                      <!-- Sale badge-->
                    <div class="badge btn-danger text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Live</div>
                      <!-- Product image-->
                    <video autoplay loop muted poster="{{ i.video }}" width="auto" height="600px" preload="bbb" src = "{{ i.getvideo }}" type="video/mp4">
                        <source src = "{{ i.getvideo }}"  type="video/mp4" >
                    </video>
                      <!-- <video class="card-img-top" src="{{ i.video }}" style = "width: 206px; height: 250px;" /> -->
                      <!-- Product details-->
                      <div class="card-body p-4">
                          <div class="text-center">
                              <!-- Product name-->
                              <h5 class="fw-bolder"><a href="{% url 'live:detail' i.id %}">{{ i.title }}</a></h5>
                              <!-- Product price-->
                              {{ i.shortcon }} 
                          </div>
                      </div>
                      <!-- Product actions-->
                      <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                          <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">{{ i.viewcount }}</a></div>
                      </div>
                  </div>
              </div>
              {% endfor %}
              {% else %}
              <h5> 현재 진행중인 라이브가 없습니다. </h5>
              {% endif %}
          </div>
      </div>
  </section>
  <!-- Footer-->
  <footer class="py-5 bg-dark">
      <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
  </footer>
  <!-- Bootstrap core JS-->
  <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script> -->
  <!-- Core theme JS-->
  <!-- <script src="js/scripts.js"></script> -->
</body>
</html>

{% endblock %}